### PR TITLE
105: Vendor Cascade Layer

### LINKED ISSUE #105: Add postcss-import and vendor layer
Add a vendor layer for third-party CSS files, so that components can override them, and add postcss-import to allow for importing of and inlining CSS files from node_modules.

Example use case: adding the base slider styles from SplideJS

### PR DESCRIPTION
**Pull request by SirJohn96**
Closes #105 

Adds the postcss-import plugin and uses it to handle most CSS imports (with the exception of anything in the mixins directory, which still needs to go through postcss-advanced-variables) to work. This allows CSS from node_modules to be imported in the newly-created vendor layer.

Example, in a component that uses Splide:
```
@import '@splidejs/splide/dist/css/splide.min.css' layer(vendor);

@layer components {
  // Your specific CSS goes here
}
```

That ensures that component-specific CSS has a later layer order, and thus greater specificity, than the base CSS provided by the vendor. Note that, as in the example here, for this to work you have to import the module CSS in your .module.css file, not your .tsx file.

### CODE REVIEW

**Comment by kmonahan** [comment]
Hey @SirJohn96 , one issue I've run into in another project is that both `postcss-import` and `postcss-advanced-variables` want to handle imports. We likely want `postcss-import` to handle everything _except_ imports of mixins, which `postcss-advanced-variables` needs in order to then use those mixins.

I ended up doing:
```
plugins: {
    '@csstools/postcss-global-data': {
      files: ['./source/00-config/vars/breakpoints.css'],
    },
    'postcss-import': {
      filter: url => {
        return url.indexOf('mixins') === -1;
      },
    },
    'postcss-advanced-variables': {
      importPaths: [path.resolve(__dirname, './source/00-config')],
      importFilter: id => {
        return id.indexOf('mixins') > -1;
      },
    },
    [require.resolve('./lib/iff.js')]: {},
    ...
```

but definitely open to ideas as I'm not sure that's the best solution; just the one that worked. 

It looks like your PR here adds postcss-import lower in the order, which I'm not sure we want to do. Their docs recommend making it one of the first plugins so that the other PostCSS plugins can then process all of the imported CSS. I think we are going to need to handle the conflict between postcss-import and postcss-advanced-variables in some fashion, even if it's not what I went with above.

**Comment by SirJohn96** [comment]
Hey @kmonahan,
My knowledge is definitely very limited here so I don't mind using your solution as it does make sense to me based off the limited research I did.

**Comment by SirJohn96** [comment]
I found some potential issues. I'm investigating.

**Comment by kmonahan** [comment]
@tomealter Adding you as a reviewer here since this evolved from what we originally did for SI Resilience

**Review by kmonahan — APPROVED** [review]

**Pull request merged**
